name: wallyhub
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  cached_network_image: ^3.2.3
  cloud_firestore: ^4.7.1
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.6.1
  firebase_core: ^2.13.0
  firebase_dynamic_links: ^5.3.3
  firebase_messaging: ^14.6.2
  firebase_storage: ^11.2.1
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.0
  flutter_custom_tabs: ^1.0.4
  flutter_spinkit: ^5.2.0
  flutter_staggered_grid_view: ^0.4.0
  font_awesome_flutter: ^10.4.0
  google_ml_kit: ^0.14.0
  google_mlkit_image_labeling: ^0.6.0
  google_sign_in: ^6.1.1
  image_picker: ^0.8.7+5
  share_plus: ^7.0.2

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  adaptive_icon_background: "assets/logo_background.png"
  adaptive_icon_foreground: "assets/logo_foreground.png"

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: productsans
      fonts:
        - asset: assets/ProductSans-Regular.ttf
