// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDep2ZEAqY4J0a2-cX_U26sTFWy9za3_04',
    appId: '1:397543740492:web:fc3f832e8ba2f2e56f10e9',
    messagingSenderId: '397543740492',
    projectId: 'wallyhub-36df2',
    authDomain: 'wallyhub-36df2.firebaseapp.com',
    storageBucket: 'wallyhub-36df2.appspot.com',
    measurementId: 'G-CJLW8G5N35',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7GwVkKoTLu0xiUyye6AdJuMSlJdru5yc',
    appId: '1:397543740492:android:e6f38ff2e81fc1f16f10e9',
    messagingSenderId: '397543740492',
    projectId: 'wallyhub-36df2',
    storageBucket: 'wallyhub-36df2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANMKC4IkIkTSz8weePCclMjkhyz6Ny6H0',
    appId: '1:397543740492:ios:8a0f57b5e5a852dc6f10e9',
    messagingSenderId: '397543740492',
    projectId: 'wallyhub-36df2',
    storageBucket: 'wallyhub-36df2.appspot.com',
    iosClientId: '397543740492-j4e538lsf1juiicue7ilv6u77l1h38cc.apps.googleusercontent.com',
    iosBundleId: 'com.example.wallyhub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANMKC4IkIkTSz8weePCclMjkhyz6Ny6H0',
    appId: '1:397543740492:ios:8a0f57b5e5a852dc6f10e9',
    messagingSenderId: '397543740492',
    projectId: 'wallyhub-36df2',
    storageBucket: 'wallyhub-36df2.appspot.com',
    iosClientId: '397543740492-j4e538lsf1juiicue7ilv6u77l1h38cc.apps.googleusercontent.com',
    iosBundleId: 'com.example.wallyhub',
  );
}
